### ISSUE TITLE
Fix "No token registered for address"

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#13]
Sometimes when running a scenario an error happens in the logs saying that the Token Address wasn't registered. However the SP continues and doesn't fail until an API call is made in the PFS that doesn't know the token address.

See attached logs: https://gist.github.com/czepluch/31448fa8598de968004de7f6c1d48228

Error first occurs in line 58, but doesn't fail until line 90.

**Comment by eorituz** [comment]
I think that might be related to https://github.com/raiden-network/raiden/issues/4498 . 
Since Raiden didn't replay all state changes before starting the Raiden service it is possible that the SP requested the token address before the Raiden client processed the block where the token was registered.
