### ISSUE TITLE
The default minted amount of RDN Tokens of the UDC is not sufficient for some scenarios

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/scenario-player#218]
At the moment nodes seem to get 1000 Test-RDN Rai tokens at the start of a scenario when `udc` is enabled. Nodes for the basic functionalities scenario, see [here](https://github.com/raiden-network/raiden/pull/4499), needs more of these tokens. 

Can this be a quick fix? Then we can test the new basic functionality scenario.

**Comment by nlsdfnbch** [comment]
The template you used is for Service Epics, which this clearly is not - I did add some bug report templates now, in order to avoid this sort of confusion. I went ahead and updated your issue.

>Can this be a quick fix?

To clarify: There are no "quick fixes" - there are fixes, and there are features. We can release at any commit, so there should be no need to call these fixes "quick fixes", as that implies they're somehow dirty hacks. And we don't do dirty hacks in this hood.

Back to the topic at hand:

I believe this issue encompasses two actual issues, a fix and a feature request:

- [ ] FIX: Update the (currently) fixed amount of minted RDN tokens, so that the new scenarios can run.
- [ ] FEATURE: Implement the option to specify the amount of RDN tokens minted in the scenario yaml.


As the work required to implement the feature is arguably small, I would suggest skipping the fix and going for the feature directly.

**Comment by christianbrb** [comment]
@Dominik1999 is testing with #135

**Comment by christianbrb** [comment]
@Dominik1999 
> yes I tested it locally yesterday and it worked

@nlsdfnbch This can be released

**Comment by nlsdfnbch** [comment]
Release with `0.3.0` (https://github.com/raiden-network/scenario-player/pull/232)
