### ISSUE TITLE
Run nightlies against Antifragile crocodile

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/scenario-player#252]
Currently nightlies are using the latest commit of the `develop` branch in hte raiden repo.

Temporarily use version `v0.100.5a0` instead.

@Dominik1999 , could you provide the rationale behind this requesst? @christianbrb has some concerns with running tests on an already tested release.

**Comment by Dominik1999** [comment]
hey there,

we need stable services for the ETH Berlin Hackathon this weekend. Hackers in ETH Berlin will use Antifragile Crocodile. 
Since everything is connected, we do not upgrade the deployed services. But since yesterday our client dev branch is on a new contract version. So when you run the Scenario Player on the latest Raiden Client Nightlies, it will not find a pathfinding service and crashes.

The alternative of deploying different services on different versions was compared to the suggested change the worse option.
