### ISSUE TITLE
Check what happened with tp04 Mon 09th

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/scenario-player#451]
Description
=========
- check DockerContainer
- restart matrix servers
- check with @ulope and description of system requirements for RSB
- check how to get a warning and monitor RSB, also align with @palango

**Comment by nlsdfnbch** [comment]
As it turns out, transport04 ran out of disk space.
https://github.com/raiden-network/raiden/issues/5462 May yield a script that will allow us to prune its size.

Steps to take:
- Enable disk-space monitoring for *all* transport servers.
- Enable Pruning script for all transport servers.
- Check with @palango or @ulope as to what a sensible disk space may be for the droplets, and at what rate we should run any potential pruning.
