### ISSUE TITLE
Reuse the Janitor from Raiden - replace mirakuru

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/scenario-player#468]
The current implementation is using a hot-loop to monitor the state of spawned Raiden processes.

https://github.com/raiden-network/scenario-player/blob/511a33ab6fbb234182184761ee44d1bf4e6912db/scenario_player/node_support.py#L547-L562

This is unnecessary since the gevent library provides an `AsyncResult` for the exit status of a `Popen` subprocess.

I'd recommend just reusing Raiden's Janitor implementation (instead of mirakuru and the current existing monitor), which has less code and implements the same functionality while handling corner cases (namely cleaning resources on exit):

https://github.com/raiden-network/raiden/blob/919115d4f140403e3b12e57bdf93bfcd80e7b5ff/tools/debugging/stress_test_transfers.py#L138-L218

Implementation:
- [x] Decide whether we want to check free ports during startup?
- [ ] Do we need healthchecks for running processes? (Probably not necessary according to @karlb and @palango) 
- [x] we do need a startup check, wait for nodes being up before starting the tasks
- [x] Replace mirakuru with Janitor

Testing:
- [ ] Run scenario player smoketest
- [x] Run simple scenario to test basic startup
- [x] Run scenario that stops and starts raiden node as part of the scenario
- [x] Add bug to Raiden and run scenario to test error handling. Expected:
  - [x] Original exception must be visible
  - [x] Other processes must be stopped cleanly
  - [x] No raiden processes must be left running when SP has finished
- [x] Processes are stopped when leaving the UI before the scenario has finished

**Comment by palango** [comment]
So after looking into this a bit I'm torn if this is worth implementing.

The idea was to get rid of mirakuru all together.
We currently use it in three places:
- In the SP to run and monitor Raiden nodes
- In the integration tests to run Ethereum nodes
- In the integration tests to run Matrix servers

We have two slightly different implementations in raiden and the SP, and it makes sense to unify them.

However, in order to get rid of mirakuru we'd basically reimplement the whole thing with some changes to process handling, which I don't think is useful.
