### ISSUE TITLE
Remove `/rpc/transactions` and `/rpc/contract` services

### ISSUE THREAD

**Issue by palango** [raiden-network/scenario-player#502]
In https://github.com/raiden-network/scenario-player/issues/495 we decided that we don't need the service architecture at the moment and want to simplify the code. This tasks tracks the implementation.

- [ ] Remove the `/rpc/transactions` endpoint
- [ ] Remove the `/rpc/contract` endpoint
- [ ] Remove service architecture infrastructure

**Comment by Dominik1999** [comment]
@hackaugusto please refine that issue or even split into 8 SP issues

**Comment by hackaugusto** [comment]
Current issue: How to expose the configuration from the Raiden node?

- Token network registry:

https://github.com/raiden-network/scenario-player/blob/f3075af5ce6ee113e17db76076f19789cdc2d435/scenario_player/runner.py#L415-L427

Used here:

https://github.com/raiden-network/scenario-player/blob/f3075af5ce6ee113e17db76076f19789cdc2d435/scenario_player/runner.py#L257-L271

- user deposit and the smart contract bundle:

https://github.com/raiden-network/scenario-player/blob/f3075af5ce6ee113e17db76076f19789cdc2d435/scenario_player/utils/legacy.py#L301-L328

**Comment by hackaugusto** [comment]
### Plan 1 [Effort ?]
 
- [ ] Add a command to Raiden to export the configuration (smart contract version and addresses)
- [ ] Use this command in the scenario player to retrieve the correct values, and instantiate the proxies in the scenario player against the correct smart contracts
- [ ] Run the setup of the environment in the scenario player using the above contracts
  - [ ] Mint utility tokens
  - [ ] Transfer utility tokens to Raiden accounts
  - [ ] Transfer Ether to the Raiden nodes
  - [ ] If necessary: Deploy the token smart contract to be used by the scenario
  - [ ] If necessary: Register the token in the token network registry

##### Benefit

This would remove inconsistencies among the Raiden and Scenario Player, fixing possible bugs due to dependencies mismatches.

##### Downside

Complexity, slow to implement

### Plan 2 [Effort 13]

Ignore the inconsistency, and use the Scenario Player's  `raiden-contract` and `raiden` dependencies.

- [ ] Use the `RAIDEN_CONTRACT_VERSION` from the `raiden` repo.
- [ ] And the `get_contracts_deployment_info` from the `raiden-contracts`.

##### Benefit
Faster to implement
##### Downside
This will eventually lead to unexpected failures, if the version of Raiden executed by the scenario player uses a different version of the smart contracts. This can happen if there is a new release of the `raiden-contracts` repo that was updated in the `raiden` repo but not in the `scenario-player` repo. However, this should not happen that often.
