### ISSUE TITLE
Run SP against demo env with release 1.2.x

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/scenario-player#666]
We need to assess the state of the demo environment services and their compatibility with the latest release.

This can be done with a local scenario player run.

**Comment by ezdac** [comment]
OK, just to clarify - because I might have misunderstood this.
I assumed this is talking about testing the current 1.2.0 release against the demo-env services? Is this correct?

**Comment by ezdac** [comment]
After quite some hassle with dependency tooling and local installations, some initial findings:

- The version check for the Ethereum node is preventing running 1.2.0 on the current ethnodes, since both the parity and geth versions running there are higher than the maximum allowed by the version check. Also the `Web3.clientVersion` was renamed from `Parity` to `OpenEthereum`, which introduces an additional condition that makes the version check fail.

After making the version check more promiscuous, I could not progress to the state where I got a proper environment for running the SP locally - this was mainly due to high load on our ethnodes, as well as the slow sync-times for a local node.
Currently, I seem to be able to not get RequestTimeouts related issues.

Some findings:
- Demo-Env runs raiden-services v.0.10.0
- PFS on demo-env does NOT expose the `/_debug/` endpoint, so the standard `AssertPFSHistoryTask` will not work and crash the SP run because of `404` errors.

**Comment by ezdac** [comment]
We will most likely directly update the demo-env to an RSB that will be compatible with `raiden-2.0.0`.

If we happen to decide against that:
I did some initial work for a possible `raiden-1.2.1` release that is compatible with the current Ethereum nodes in our network - [ezdac/raiden/1.2.1-geth-1.10.2](https://github.com/ezdac/raiden/tree/1.2.1-geth-1.10.2).

The SP had to be updated to this Raiden version, and also the aforementioned handling of PFS's `404` responses on the `/_debug/` endpoint had to be handled - [ezdac/scenario-player/1.2.1-get-1.10.2-compatibility](https://github.com/ezdac/scenario-player/tree/1.2.1-geth-1.10.2-compatibility)

The above was run locally against the current demo-env:
- `bf1` - I couldn't get it to finish, since it was blocking in a `DepositTask` forever (no further investigation, could be local setup problem)
- `pfs1` did finish successfully

No further investigation was conducted (yet)
